### ISSUE TITLE
fetcher.fetchGuild does not work.

### ISSUE THREAD

**Issue by deepsarda** [discordeno/cache-proxy#14]
![image](https://user-images.githubusercontent.com/92147339/199244824-53609df5-0689-46bd-8d1d-073c345e58d8.png)
`const guild = await bot.helpers.getGuild(id);` throws error.
Error: [403] The Authorization token you passed did not have permission to the resource.
{"message":"Missing Access","code":50001}

**Comment by itohatweb** [comment]
Are you sure that you are actually providing the id of a guild which your bot is in?

**Comment by deepsarda** [comment]
This is a ss of [index.ts](https://github.com/discordeno/cache-proxy/blob/b2284a7d3268fd0e4106f668b28896db7dd75868/index.ts#L233).

The link will take you to that line.

**Comment by itohatweb** [comment]
That's not answering my question though.

**Comment by deepsarda** [comment]
> Are you sure that you are actually providing the id of a guild which your bot is in?

This is happening inside the message transformer.
I am not doing anything.

**Comment by deepsarda** [comment]
#16 Explains this issue.
